apply plugin: 'com.android.application'

android {
    namespace "com.wsgoat.whatsapp"
    compileSdk 34

    defaultConfig {
        applicationId "com.wsgoat.whatsapp"
        minSdk 22
        targetSdk 34
        versionCode 1
        versionName "1.0.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
}
